### PR TITLE
Prefix index name with name of containing table to ensure uniqueness.

### LINKED ISSUE #35: Index naming change to IX_table_column
two table has the same column with [Index] will failed when create databases: the index is alread exsist

class a
{
  [Index]
  public string c {get;set;}
}
class b
{
  [Index]
  public string c {get;set;}
}

### PR DESCRIPTION
**Pull request by Rychard**
Prefixes the name of an index with the name of the table that contains the column it is created on.  No changes are made to indexes that are defined explicitly via the fluent API or `IndexAttribute`.

Fixes #35.

When you define at least two classes containing navigation properties to a common third class, and both navigation properties are mapped (via convention) to properties with identical names, the following error is received:

```
index IX_<PropertyName> already exists
```

This occurs because Entity Framework will automatically create an `index` for the non-source columns participating in a foreign-key relationship.  This is done to improve the performance when querying against the relevant columns.

Here's some code that should allow you to reproduce the issue:

``` csharp

public class Category 
{
    public int CategoryID {get; set;}
    public string CategoryName {get; set;}
}

public class Thing
{
    public int ThingID {get; set;}
    public string ThingName {get; set;}

    // Implicitly creates an index named "IX_CategoryID"
    public int CategoryID {get; set;} 
    public virtual Category Category {get; set;}
}

public class Stuff
{
    public int StuffID {get; set;}
    public string StuffName {get; set;}

    // Attempts to create another index, also named "IX_CategoryID"
    // As this index was already created earlier, we get an error:
    // "index IX_CategoryID already exists"
    public int CategoryID {get; set;} 
    public virtual Category Category {get; set;}
}

```

### CODE REVIEW

File: SQLite.CodeFirst/Builder/CreateIndexStatementBuilder.cs [hunk 1]
```diff
@@ -54,9 +54,9 @@ public CreateIndexStatementCollection BuildStatement()
             return new CreateIndexStatementCollection(createIndexStatments.Values);
         }
 
-        private static string GetIndexName(IndexAttribute index, EdmProperty property)
+        private string GetIndexName(IndexAttribute index, EdmProperty property)
         {
-            return index.Name ?? "IX_" + property.Name;
+            return index.Name ?? string.Format("IX_{0}_{1}", entitySet.Table, property.Name);
```
Comment (msallin) [inline SQLite.CodeFirst/Builder/CreateIndexStatementBuilder.cs]: There is an extension Method "GetTableName()"  `SQLite.CodeFirst.Extensions.EntityTypeExtension`. Can you use this method to get the table Name instead of `entitySet.Table`?

**Comment by msallin** [comment]
Thanks for your PR.
Please see my line note.

Greetings Marc

**Comment by Rychard** [comment]
Thanks for the quick response.

I've updated the original commit to use the extension method, per your request.
